package dev.dagxam.bedrockores.node;

import org.bukkit.Material;
import org.bukkit.plugin.Plugin;
import java.io.File; import java.sql.*; import java.util.*;

/** SQLite-хранилище. Все JDBC-операции синхронизированы вокруг одного соединения. */
final class NodeDatabase implements AutoCloseable {
    private final Connection connection;
    NodeDatabase(Plugin plugin)throws SQLException{File f=new File(plugin.getDataFolder(),"nodes.db");connection=DriverManager.getConnection("jdbc:sqlite:"+f.getAbsolutePath());try(Statement s=connection.createStatement()){s.execute("PRAGMA journal_mode=WAL");s.execute("PRAGMA synchronous=NORMAL");s.execute("PRAGMA temp_store=MEMORY");s.execute("CREATE TABLE IF NOT EXISTS nodes (world TEXT NOT NULL,x INTEGER NOT NULL,y INTEGER NOT NULL,z INTEGER NOT NULL,type TEXT NOT NULL,hits INTEGER NOT NULL,max_hits INTEGER NOT NULL,PRIMARY KEY(world,x,y,z))");s.execute("CREATE INDEX IF NOT EXISTS idx_nodes_chunk ON nodes(world,(x >> 4),(z >> 4))");s.execute("CREATE TABLE IF NOT EXISTS respawns (world TEXT NOT NULL,x INTEGER NOT NULL,y INTEGER NOT NULL,z INTEGER NOT NULL,type TEXT NOT NULL,due_at INTEGER NOT NULL,PRIMARY KEY(world,x,y,z))");s.execute("CREATE INDEX IF NOT EXISTS idx_respawns_chunk ON respawns(world,(x >> 4),(z >> 4))");s.execute("CREATE INDEX IF NOT EXISTS idx_respawns_due ON respawns(due_at)");s.execute("CREATE TABLE IF NOT EXISTS processed_chunks (world TEXT NOT NULL,x INTEGER NOT NULL,z INTEGER NOT NULL,PRIMARY KEY(world,x,z))");}}
    synchronized List<NodeManager.NodeEntry> loadNodes(UUID w,int cx,int cz)throws SQLException{List<NodeManager.NodeEntry>o=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("SELECT x,y,z,type,hits,max_hits FROM nodes WHERE world=? AND (x >> 4)=? AND (z >> 4)=?")){p.setString(1,w.toString());p.setInt(2,cx);p.setInt(3,cz);try(ResultSet r=p.executeQuery()){while(r.next())o.add(new NodeManager.NodeEntry(w,r.getInt(1),r.getInt(2),r.getInt(3),Material.valueOf(r.getString(4)),r.getInt(5),r.getInt(6)));}}return o;}
    synchronized List<NodeManager.RespawnEntry> loadDueRespawns(UUID w,int cx,int cz,long now)throws SQLException{List<NodeManager.RespawnEntry>o=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("SELECT x,y,z,type,due_at FROM respawns WHERE world=? AND (x >> 4)=? AND (z >> 4)=? AND due_at<=?")){p.setString(1,w.toString());p.setInt(2,cx);p.setInt(3,cz);p.setLong(4,now);try(ResultSet r=p.executeQuery()){while(r.next())o.add(new NodeManager.RespawnEntry(w,r.getInt(1),r.getInt(2),r.getInt(3),Material.valueOf(r.getString(4)),r.getLong(5)));}}return o;}
    synchronized boolean isProcessed(UUID w,int x,int z)throws SQLException{try(PreparedStatement p=connection.prepareStatement("SELECT 1 FROM processed_chunks WHERE world=? AND x=? AND z=?")){p.setString(1,w.toString());p.setInt(2,x);p.setInt(3,z);try(ResultSet r=p.executeQuery()){return r.next();}}}
    synchronized void saveDirty(Collection<NodeManager.NodeEntry>upN,Collection<NodeManager.NodeEntry>delN,Collection<NodeManager.RespawnEntry>upR,Collection<NodeManager.RespawnEntry>delR,Collection<NodeManager.ChunkEntry>pc)throws SQLException{connection.setAutoCommit(false);try{try(PreparedStatement up=connection.prepareStatement("INSERT INTO nodes(world,x,y,z,type,hits,max_hits) VALUES(?,?,?,?,?,?,?) ON CONFLICT(world,x,y,z) DO UPDATE SET type=excluded.type,hits=excluded.hits,max_hits=excluded.max_hits");PreparedStatement del=connection.prepareStatement("DELETE FROM nodes WHERE world=? AND x=? AND y=? AND z=?")){for(NodeManager.NodeEntry e:upN){up.setString(1,e.world().toString());up.setInt(2,e.x());up.setInt(3,e.y());up.setInt(4,e.z());up.setString(5,e.type().name());up.setInt(6,e.hits());up.setInt(7,e.maxHits());up.addBatch();}for(NodeManager.NodeEntry e:delN){del.setString(1,e.world().toString());del.setInt(2,e.x());del.setInt(3,e.y());del.setInt(4,e.z());del.addBatch();}up.executeBatch();del.executeBatch();}try(PreparedStatement up=connection.prepareStatement("INSERT INTO respawns(world,x,y,z,type,due_at) VALUES(?,?,?,?,?,?) ON CONFLICT(world,x,y,z) DO UPDATE SET type=excluded.type,due_at=excluded.due_at");PreparedStatement del=connection.prepareStatement("DELETE FROM respawns WHERE world=? AND x=? AND y=? AND z=?")){for(NodeManager.RespawnEntry e:upR){up.setString(1,e.world().toString());up.setInt(2,e.x());up.setInt(3,e.y());up.setInt(4,e.z());up.setString(5,e.type().name());up.setLong(6,e.dueAtMillis());up.addBatch();}for(NodeManager.RespawnEntry e:delR){del.setString(1,e.world().toString());del.setInt(2,e.x());del.setInt(3,e.y());del.setInt(4,e.z());del.addBatch();}up.executeBatch();del.executeBatch();}try(PreparedStatement p=connection.prepareStatement("INSERT OR IGNORE INTO processed_chunks(world,x,z) VALUES(?,?,?)")){for(NodeManager.ChunkEntry e:pc){p.setString(1,e.world().toString());p.setInt(2,e.x());p.setInt(3,e.z());p.addBatch();}p.executeBatch();}connection.commit();}catch(SQLException e){connection.rollback();throw e;}finally{connection.setAutoCommit(true);}}
    @Override public synchronized void close()throws SQLException{connection.close();}
}
