package dev.dagxam.bedrockores.node;

import net.kyori.adventure.text.Component;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.ExperienceOrb;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.block.*;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.player.*;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.Plugin;
import java.util.*;

/** Обработка добычи с русскими сообщениями и dirty-сохранением прогресса. */
public class OreListeners implements Listener {
    private static final String USE_PERMISSION="bedrockores.use"; private final Plugin plugin; private final NodeManager nm; private final Random rnd=new Random();
    private static class HoldSession{final Location loc;long lastSeenNs;HoldSession(Location l,long n){loc=l;lastSeenNs=n;}} private final Map<UUID,HoldSession>holds=new HashMap<>();
    public OreListeners(Plugin p,NodeManager n){plugin=p;nm=n;int t=Math.max(1,p.getConfig().getInt("производительность.интервал-ударов-тиков",5));Bukkit.getScheduler().runTaskTimer(p,this::tickHolds,t,t);} private boolean isAllowedPickaxe(ItemStack t){if(t==null)return false;Material m=t.getType();return m==Material.DIAMOND_PICKAXE||m==Material.NETHERITE_PICKAXE;}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=false) public void onLeftClick(PlayerInteractEvent e){if(e.getAction()!=Action.LEFT_CLICK_BLOCK||e.getHand()!=EquipmentSlot.HAND)return;Block b=e.getClickedBlock();if(b==null||!nm.isNode(b.getLocation()))return;Player p=e.getPlayer();if(!p.hasPermission(USE_PERMISSION)){e.setCancelled(true);refreshClientBlock(b);p.sendActionBar(Component.text("У вас нет права: "+USE_PERMISSION));return;}if(p.getGameMode()==GameMode.CREATIVE){e.setCancelled(true);refreshClientBlock(b);p.sendActionBar(Component.text("В режиме CREATIVE добыча рудных узлов отключена."));return;}if(!isAllowedPickaxe(p.getInventory().getItemInMainHand())){e.setCancelled(true);refreshClientBlock(b);p.sendActionBar(Component.text("Для добычи нужна алмазная или незеритовая кирка."));return;}e.setCancelled(true);refreshClientBlock(b);startOrUpdateHold(p,b.getLocation());}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=false) public void onBlockDamage(BlockDamageEvent e){Block b=e.getBlock();if(!nm.isNode(b.getLocation()))return;Player p=e.getPlayer();e.setCancelled(true);e.setInstaBreak(false);refreshClientBlock(b);if(!p.hasPermission(USE_PERMISSION)||p.getGameMode()==GameMode.CREATIVE)return;if(!isAllowedPickaxe(p.getInventory().getItemInMainHand())){p.sendActionBar(Component.text("Для добычи нужна алмазная или незеритовая кирка."));return;}startOrUpdateHold(p,b.getLocation());}
    @EventHandler(ignoreCancelled=true) public void onSwing(PlayerAnimationEvent e){HoldSession h=holds.get(e.getPlayer().getUniqueId());if(h==null)return;Block b=e.getPlayer().getTargetBlockExact(6);if(b!=null&&sameBlock(h.loc,b.getLocation()))h.lastSeenNs=System.nanoTime();}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=false) public void onBlockBreak(BlockBreakEvent e){if(!nm.isNode(e.getBlock().getLocation()))return;e.setCancelled(true);refreshClientBlock(e.getBlock());}
    @EventHandler public void onQuit(PlayerQuitEvent e){holds.remove(e.getPlayer().getUniqueId());}
    private void tickHolds(){if(holds.isEmpty())return;long now=System.nanoTime(),timeout=plugin.getConfig().getLong("производительность.таймаут-удержания-мс",400L)*1_000_000L;int budget=Math.max(1,plugin.getConfig().getInt("производительность.максимум-ударов-за-тик",60)),done=0;Iterator<Map.Entry<UUID,HoldSession>>it=holds.entrySet().iterator();while(it.hasNext()&&done<budget){Map.Entry<UUID,HoldSession>e=it.next();Player p=Bukkit.getPlayer(e.getKey());HoldSession h=e.getValue();if(p==null||!p.isOnline()||!p.hasPermission(USE_PERMISSION)||p.getGameMode()==GameMode.CREATIVE||!isAllowedPickaxe(p.getInventory().getItemInMainHand())||now-h.lastSeenNs>timeout){it.remove();continue;}World w=h.loc.getWorld();if(w==null||!w.isChunkLoaded(h.loc.getBlockX()>>4,h.loc.getBlockZ()>>4)||!nm.isNode(h.loc)){it.remove();continue;}NodeData d=nm.getNode(h.loc);if(d==null){it.remove();continue;}handleHit(p,h.loc.getBlock(),d);done++;}}
    private void startOrUpdateHold(Player p,Location l){holds.put(p.getUniqueId(),new HoldSession(l,System.nanoTime()));} private boolean sameBlock(Location a,Location b){return a.getWorld()==b.getWorld()&&a.getBlockX()==b.getBlockX()&&a.getBlockY()==b.getBlockY()&&a.getBlockZ()==b.getBlockZ();} private void refreshClientBlock(Block b){Bukkit.getScheduler().runTask(plugin,()->b.getState().update(true,false));}
    private void handleHit(Player p,Block b,NodeData d){giveOreDrop(p,b,d);d.hitsRemaining--;if(d.hitsRemaining<=0){b.setType(Material.BEDROCK,false);b.getWorld().playSound(b.getLocation().add(.5,.5,.5),Sound.BLOCK_ANVIL_PLACE,.7f,.8f);nm.removeNode(b.getLocation());nm.scheduleRespawn(b.getLocation(),d.oreMaterial);p.sendActionBar(Component.text("Рудный узел полностью исчерпан: 0/"+d.maxHits));}else{nm.markNodeDirty(b.getLocation());b.getWorld().playSound(b.getLocation().add(.5,.5,.5),Sound.BLOCK_STONE_HIT,.8f,1f);b.getWorld().spawnParticle(Particle.BLOCK,b.getLocation().add(.5,.5,.5),12,.3,.3,.3,0,b.getBlockData());showProgress(p,b.getLocation(),d);}}
    private void showProgress(Player p,Location l,NodeData d){try{p.sendBlockDamage(l,Math.min(.98f,Math.max(0f,d.progress())));}catch(Throwable ignored){}p.sendActionBar(Component.text("Осталось ударов: "+d.hitsRemaining+"/"+d.maxHits));}
    private void giveOreDrop(Player p,Block b,NodeData d){ItemStack tool=p.getInventory().getItemInMainHand();int f=tool==null?0:tool.getEnchantmentLevel(Enchantment.FORTUNE);boolean fortune=plugin.getConfig().getBoolean("fortune.включено",true);int amount=baseAmount(d.oreMaterial);if(fortune&&f>0)amount*=1+rnd.nextInt(f+1);Material drop=dropFor(d.oreMaterial);if(drop==null)return;ItemStack item=new ItemStack(drop,Math.max(1,amount));if(plugin.getConfig().getBoolean("производительность.выдавать-предмет-сразу-в-инвентарь",true)){for(ItemStack rest:p.getInventory().addItem(item).values())b.getWorld().dropItemNaturally(b.getLocation().add(.5,.5,.5),rest);}else b.getWorld().dropItemNaturally(b.getLocation().add(.5,.5,.5),item);int xp=xpFor(d.oreMaterial);if(xp>0){String mode=plugin.getConfig().getString("производительность.режим-опыта","direct");if("direct".equalsIgnoreCase(mode))p.giveExp(xp);else{ExperienceOrb o=b.getWorld().spawn(b.getLocation().add(.5,.5,.5),ExperienceOrb.class);o.setExperience(xp);}}}
    private int baseAmount(Material o){return switch(o){case DEEPSLATE_REDSTONE_ORE,DEEPSLATE_LAPIS_ORE->3+rnd.nextInt(3);case DEEPSLATE_COPPER_ORE->1+rnd.nextInt(2);case NETHERITE_SCRAP->1;default->1;};} private Material dropFor(Material o){return switch(o){case DEEPSLATE_REDSTONE_ORE->Material.REDSTONE;case DEEPSLATE_LAPIS_ORE->Material.LAPIS_LAZULI;case DEEPSLATE_COPPER_ORE->Material.RAW_COPPER;case DEEPSLATE_GOLD_ORE->Material.RAW_GOLD;case DEEPSLATE_IRON_ORE->Material.RAW_IRON;case DEEPSLATE_DIAMOND_ORE->Material.DIAMOND;case DEEPSLATE_EMERALD_ORE->Material.EMERALD;case DEEPSLATE_COAL_ORE->Material.COAL;case NETHERITE_SCRAP->Material.NETHERITE_SCRAP;default->null;};} private int xpFor(Material o){return switch(o){case DEEPSLATE_REDSTONE_ORE,DEEPSLATE_LAPIS_ORE->3;case DEEPSLATE_DIAMOND_ORE,DEEPSLATE_EMERALD_ORE->5;default->0;};}
}
