enabled-worlds:
  - world

generation:
  layers-from-bottom: 7
  chance-per-block: 0.008
  density-multiplier: 1.0      # множитель к chance-per-block
  min-spacing: 4               # минимальная дистанция между узлами (4–5 по твоему ТЗ)
  target-per-chunk: 12         # целевое кол-во узлов на чанк
  max-per-chunk: 24            # максимум узлов на чанк (страховка)
  fill-attempts-per-node: 25   # попыток на каждый недостающий узел при доборе

fortune-enabled: true

ore-weights:
  DEEPSLATE_REDSTONE_ORE: 8
  DEEPSLATE_IRON_ORE: 6
  DEEPSLATE_GOLD_ORE: 3
  DEEPSLATE_COPPER_ORE: 4
  DEEPSLATE_COAL_ORE: 4
  DEEPSLATE_LAPIS_ORE: 3
  DEEPSLATE_DIAMOND_ORE: 1
  DEEPSLATE_EMERALD_ORE: 1

respawn:
  enabled: true
  delay-seconds: 3600   # 1 час
  
performance:
  direct-item-to-inventory: true
  xp-mode: direct           # direct | orb
  hold-hit-interval-ticks: 5
  hold-timeout-ms: 400
  max-hold-hits-per-tick: 60
  
